Added local dynamo jar and modified run-tests. So the tests can be run out of the box with './run-tests local'

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,18 +1,29 @@
 #!/bin/bash
 
 if [ "$#" -lt 1 ]; then
-    echo "Usage: $0 <env-file> [--auto]"
-    exit 1
-elif [ ! -f "$1" ]; then
-    echo "ABORTING: specified env-file not found: $1"
-    exit 1
+  echo "Usage: $0 [<env-file>|local] [--auto]"
+  exit 1
+elif [ "$1" != "local" ] && [ ! -f "$1" ]; then
+  echo "ABORTING: specified env-file not found: $1"
+  exit 1
 else
+
+  if [ "$1" = "local" ]; then
+    echo "Starting local Dynamodb"
+    java -Djava.library.path=./local-dynamo/DynamoDBLocal_lib -jar ./local-dynamo/DynamoDBLocal.jar -port 6798 -inMemory &
+    trap "pkill -f DynamoDBLocal" EXIT
+
+    export AWS_DYNAMODB_ACCESS_KEY="test"
+    export AWS_DYNAMODB_SECRET_KEY="test"
+    export AWS_DYNAMODB_ENDPOINT="http://localhost:6798"
+  else
     echo "Using $1 for IAM creds..."
     source $1
+  fi
 
-   if [ "$2" = "--auto" ]; then
-      lein test-auto
-   else
-      lein test-all
-    fi
+  if [ "$2" = "--auto" ]; then
+    lein test-auto
+  else
+    lein test-all
+  fi
 fi
